name: Build ipk for HomeProxy

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - 'htdocs/**'
      - 'po/**'
      - 'root/**'
      - 'Makefile'
      - '.github/**'
      - '!.github/ISSUE_TEMPLATE/**'

  pull_request:
    branches:
      - 'master'
      - 'dev'
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'htdocs/**'
      - 'root/**'
      - 'Makefile'
      - '.github/**'
      - '!.github/ISSUE_TEMPLATE/**'

  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'master'
      version:
        description: 'Version number'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Build ipk file
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Building from branch: ${{ github.event.inputs.branch }}"
          echo "Version: ${{ github.event.inputs.version }}"
          pushd .github
          fakeroot bash build-ipk.sh
          echo "ASSET_NAME=$(ls *.ipk)" >> $GITHUB_ENV
          popd

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ASSET_NAME }}
          path: .github/${{ env.ASSET_NAME }}
